#!/usr/bin/env python3
"""Generate include/tv_config.h from the lgtvremote-cli device store.

Reads ~/.config/lgtvremote/devices.json (LG/webOS TVs only) so the firmware
reuses the pairings you already have. The output contains client keys, so it
is gitignored.
"""
import json, os, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(os.path.expanduser("~/.config/lgtvremote/devices.json"))

def c(s):
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'

def main():
    cfg = json.loads(SRC.read_text())
    devices = cfg.get("devices", {})
    default = cfg.get("default")
    tvs = []
    for ip, d in devices.items():
        if d.get("brand", "lg").lower() != "lg":
            continue
        if not d.get("client_key"):
            continue
        tvs.append(d)
    # default TV first
    tvs.sort(key=lambda d: 0 if d.get("ip") == default else 1)
    out = ROOT / "include" / "tv_config.h"
    with out.open("w") as f:
        f.write("// Generated by tools/gen_config.py from ~/.config/lgtvremote/devices.json — do not edit, do not commit.\n")
        f.write("#pragma once\n\nstruct TVSeed { const char* name; const char* ip; const char* clientKey; const char* mac; const char* wifiMac; bool unsignedRegistration; };\n\n")
        f.write(f"#define TV_SEED_HAS_UNSIGNED 1\n#define TV_COUNT {len(tvs)}\n")
        f.write("static const TVSeed TVS[TV_COUNT] = {\n")
        for d in tvs:
            f.write(f"  {{{c(d.get('name'))}, {c(d.get('ip'))}, {c(d.get('client_key'))}, {c(d.get('mac'))}, {c(d.get('wifi_mac'))}, {'true' if d.get('lg_uses_unsigned_registration') else 'false'}}},\n")
        f.write("};\n")
    print(f"wrote {len(tvs)} TVs -> {out.relative_to(ROOT)}: " + ", ".join(f"{d.get('name')} ({d.get('ip')})" for d in tvs))

if __name__ == "__main__":
    main()
